/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.uhuru.userservice.data.kafkaRequest;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class UserCreatedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1822468022026784335L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserCreatedEvent\",\"namespace\":\"com.uhuru.userservice.data.kafkaRequest\",\"fields\":[{\"name\":\"fullName\",\"type\":\"string\"},{\"name\":\"hashedPassword\",\"type\":\"string\"},{\"name\":\"userNumber\",\"type\":\"string\"},{\"name\":\"actionDetails\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<UserCreatedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UserCreatedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<UserCreatedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<UserCreatedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<UserCreatedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this UserCreatedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a UserCreatedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a UserCreatedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static UserCreatedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence fullName;
  private java.lang.CharSequence hashedPassword;
  private java.lang.CharSequence userNumber;
  private java.lang.CharSequence actionDetails;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UserCreatedEvent() {}

  /**
   * All-args constructor.
   * @param fullName The new value for fullName
   * @param hashedPassword The new value for hashedPassword
   * @param userNumber The new value for userNumber
   * @param actionDetails The new value for actionDetails
   */
  public UserCreatedEvent(java.lang.CharSequence fullName, java.lang.CharSequence hashedPassword, java.lang.CharSequence userNumber, java.lang.CharSequence actionDetails) {
    this.fullName = fullName;
    this.hashedPassword = hashedPassword;
    this.userNumber = userNumber;
    this.actionDetails = actionDetails;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return fullName;
    case 1: return hashedPassword;
    case 2: return userNumber;
    case 3: return actionDetails;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: fullName = (java.lang.CharSequence)value$; break;
    case 1: hashedPassword = (java.lang.CharSequence)value$; break;
    case 2: userNumber = (java.lang.CharSequence)value$; break;
    case 3: actionDetails = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'fullName' field.
   * @return The value of the 'fullName' field.
   */
  public java.lang.CharSequence getFullName() {
    return fullName;
  }


  /**
   * Sets the value of the 'fullName' field.
   * @param value the value to set.
   */
  public void setFullName(java.lang.CharSequence value) {
    this.fullName = value;
  }

  /**
   * Gets the value of the 'hashedPassword' field.
   * @return The value of the 'hashedPassword' field.
   */
  public java.lang.CharSequence getHashedPassword() {
    return hashedPassword;
  }


  /**
   * Sets the value of the 'hashedPassword' field.
   * @param value the value to set.
   */
  public void setHashedPassword(java.lang.CharSequence value) {
    this.hashedPassword = value;
  }

  /**
   * Gets the value of the 'userNumber' field.
   *
   * @return The value of the 'userNumber' field.
   */
  public String getUserNumber() {
    return (String) userNumber;
  }


  /**
   * Sets the value of the 'userNumber' field.
   * @param value the value to set.
   */
  public void setUserNumber(java.lang.CharSequence value) {
    this.userNumber = value;
  }

  /**
   * Gets the value of the 'actionDetails' field.
   * @return The value of the 'actionDetails' field.
   */
  public java.lang.CharSequence getActionDetails() {
    return actionDetails;
  }


  /**
   * Sets the value of the 'actionDetails' field.
   * @param value the value to set.
   */
  public void setActionDetails(java.lang.CharSequence value) {
    this.actionDetails = value;
  }

  /**
   * Creates a new UserCreatedEvent RecordBuilder.
   * @return A new UserCreatedEvent RecordBuilder
   */
  public static com.uhuru.userservice.data.kafkaRequest.UserCreatedEvent.Builder newBuilder() {
    return new com.uhuru.userservice.data.kafkaRequest.UserCreatedEvent.Builder();
  }

  /**
   * Creates a new UserCreatedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UserCreatedEvent RecordBuilder
   */
  public static com.uhuru.userservice.data.kafkaRequest.UserCreatedEvent.Builder newBuilder(com.uhuru.userservice.data.kafkaRequest.UserCreatedEvent.Builder other) {
    if (other == null) {
      return new com.uhuru.userservice.data.kafkaRequest.UserCreatedEvent.Builder();
    } else {
      return new com.uhuru.userservice.data.kafkaRequest.UserCreatedEvent.Builder(other);
    }
  }

  /**
   * Creates a new UserCreatedEvent RecordBuilder by copying an existing UserCreatedEvent instance.
   * @param other The existing instance to copy.
   * @return A new UserCreatedEvent RecordBuilder
   */
  public static com.uhuru.userservice.data.kafkaRequest.UserCreatedEvent.Builder newBuilder(com.uhuru.userservice.data.kafkaRequest.UserCreatedEvent other) {
    if (other == null) {
      return new com.uhuru.userservice.data.kafkaRequest.UserCreatedEvent.Builder();
    } else {
      return new com.uhuru.userservice.data.kafkaRequest.UserCreatedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for UserCreatedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserCreatedEvent>
    implements org.apache.avro.data.RecordBuilder<UserCreatedEvent> {

    private java.lang.CharSequence fullName;
    private java.lang.CharSequence hashedPassword;
    private java.lang.CharSequence userNumber;
    private java.lang.CharSequence actionDetails;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.uhuru.userservice.data.kafkaRequest.UserCreatedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.fullName)) {
        this.fullName = data().deepCopy(fields()[0].schema(), other.fullName);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.hashedPassword)) {
        this.hashedPassword = data().deepCopy(fields()[1].schema(), other.hashedPassword);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.userNumber)) {
        this.userNumber = data().deepCopy(fields()[2].schema(), other.userNumber);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.actionDetails)) {
        this.actionDetails = data().deepCopy(fields()[3].schema(), other.actionDetails);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing UserCreatedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.uhuru.userservice.data.kafkaRequest.UserCreatedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.fullName)) {
        this.fullName = data().deepCopy(fields()[0].schema(), other.fullName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.hashedPassword)) {
        this.hashedPassword = data().deepCopy(fields()[1].schema(), other.hashedPassword);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.userNumber)) {
        this.userNumber = data().deepCopy(fields()[2].schema(), other.userNumber);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.actionDetails)) {
        this.actionDetails = data().deepCopy(fields()[3].schema(), other.actionDetails);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'fullName' field.
      * @return The value.
      */
    public java.lang.CharSequence getFullName() {
      return fullName;
    }


    /**
      * Sets the value of the 'fullName' field.
      * @param value The value of 'fullName'.
      * @return This builder.
      */
    public com.uhuru.userservice.data.kafkaRequest.UserCreatedEvent.Builder setFullName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.fullName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'fullName' field has been set.
      * @return True if the 'fullName' field has been set, false otherwise.
      */
    public boolean hasFullName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'fullName' field.
      * @return This builder.
      */
    public com.uhuru.userservice.data.kafkaRequest.UserCreatedEvent.Builder clearFullName() {
      fullName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'hashedPassword' field.
      * @return The value.
      */
    public java.lang.CharSequence getHashedPassword() {
      return hashedPassword;
    }


    /**
      * Sets the value of the 'hashedPassword' field.
      * @param value The value of 'hashedPassword'.
      * @return This builder.
      */
    public com.uhuru.userservice.data.kafkaRequest.UserCreatedEvent.Builder setHashedPassword(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.hashedPassword = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'hashedPassword' field has been set.
      * @return True if the 'hashedPassword' field has been set, false otherwise.
      */
    public boolean hasHashedPassword() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'hashedPassword' field.
      * @return This builder.
      */
    public com.uhuru.userservice.data.kafkaRequest.UserCreatedEvent.Builder clearHashedPassword() {
      hashedPassword = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'userNumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getUserNumber() {
      return userNumber;
    }


    /**
      * Sets the value of the 'userNumber' field.
      * @param value The value of 'userNumber'.
      * @return This builder.
      */
    public com.uhuru.userservice.data.kafkaRequest.UserCreatedEvent.Builder setUserNumber(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.userNumber = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'userNumber' field has been set.
      * @return True if the 'userNumber' field has been set, false otherwise.
      */
    public boolean hasUserNumber() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'userNumber' field.
      * @return This builder.
      */
    public com.uhuru.userservice.data.kafkaRequest.UserCreatedEvent.Builder clearUserNumber() {
      userNumber = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'actionDetails' field.
      * @return The value.
      */
    public java.lang.CharSequence getActionDetails() {
      return actionDetails;
    }


    /**
      * Sets the value of the 'actionDetails' field.
      * @param value The value of 'actionDetails'.
      * @return This builder.
      */
    public com.uhuru.userservice.data.kafkaRequest.UserCreatedEvent.Builder setActionDetails(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.actionDetails = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'actionDetails' field has been set.
      * @return True if the 'actionDetails' field has been set, false otherwise.
      */
    public boolean hasActionDetails() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'actionDetails' field.
      * @return This builder.
      */
    public com.uhuru.userservice.data.kafkaRequest.UserCreatedEvent.Builder clearActionDetails() {
      actionDetails = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UserCreatedEvent build() {
      try {
        UserCreatedEvent record = new UserCreatedEvent();
        record.fullName = fieldSetFlags()[0] ? this.fullName : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.hashedPassword = fieldSetFlags()[1] ? this.hashedPassword : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.userNumber = fieldSetFlags()[2] ? this.userNumber : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.actionDetails = fieldSetFlags()[3] ? this.actionDetails : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UserCreatedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<UserCreatedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UserCreatedEvent>
    READER$ = (org.apache.avro.io.DatumReader<UserCreatedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.fullName);

    out.writeString(this.hashedPassword);

    out.writeString(this.userNumber);

    out.writeString(this.actionDetails);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.fullName = in.readString(this.fullName instanceof Utf8 ? (Utf8)this.fullName : null);

      this.hashedPassword = in.readString(this.hashedPassword instanceof Utf8 ? (Utf8)this.hashedPassword : null);

      this.userNumber = in.readString(this.userNumber instanceof Utf8 ? (Utf8)this.userNumber : null);

      this.actionDetails = in.readString(this.actionDetails instanceof Utf8 ? (Utf8)this.actionDetails : null);

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.fullName = in.readString(this.fullName instanceof Utf8 ? (Utf8)this.fullName : null);
          break;

        case 1:
          this.hashedPassword = in.readString(this.hashedPassword instanceof Utf8 ? (Utf8)this.hashedPassword : null);
          break;

        case 2:
          this.userNumber = in.readString(this.userNumber instanceof Utf8 ? (Utf8)this.userNumber : null);
          break;

        case 3:
          this.actionDetails = in.readString(this.actionDetails instanceof Utf8 ? (Utf8)this.actionDetails : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










